ankitpokhrel/tus-php

- README.md
- example/partial.php
- example/upload.php
- example/verify.php
- src/File.php
- src/Request.php
- src/Tus/Client.php
- src/Tus/Server.php
- tests/FileTest.php
- tests/RequestTest.php
- tests/Tus/ClientTest.php
- tests/Tus/ServerTest.php
> Use user defined key instead of always using file hash as a cache key

- example/basic/index.php
- example/index.php
- example/partial/index.php
- example/uppy/index.html
- k8s/client.yml
- k8s/redis.yml
- k8s/server.yml
I have introduced 2 changes.
- update apiVersion
- add demo page
**Screenshot of demo page**
**OS:** macOS High Sierra
**version:** 10.13.6
1) `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
2) `minikube version`
```
minikube version: v0.28.2
```
3) `docker version`
```
Client:
Version:	17.12.0-ce
API version:	1.35
Go version: …
```
> update kubernetes api version; add demo page

- src/Request.php
- tests/RequestTest.php
Related to https://github.com/ankitpokhrel/tus-php/pull/82
This PR addresses the issue when Upload-Metadata has multiple metadata separated with commas as per [Tus Protocol for Upload-Metadata](https://tus.io/protocols/resumable-upload.html#upload-metadata)
> Refactor Upload-Metadata extract

- example/basic/index.php
- example/basic/upload.php
- example/basic/verify.php
After the file is uploaded on the basic example upload page. It shows the
download link on the same page. Once that download link is clicked then
it should download the uploaded file. That download link was broken.
This change fixes the same broken download link.
> fix the broken download link in example link

- example/basic/index.php
- src/Tus/Server.php
- tests/Tus/ServerTest.php
Related: #86, symfony/symfony#28743
[RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.2) states that the `HEAD` method is identical to `GET` and all major PHP frameworks silently transforms `HEAD` requests to `GET`. This causes issue when using tus-php with PHP frameworks as it treats `GET` request as a file download request. 
File download in `GET /files/<key>` request is not a part of the tus specification. So to align with others, unlike [official tus server implementation](https://github.com/tus/tusd/blob/master/unrouted_handler.go#L583), this PR moves download request to `GET /files/<key>/get` endpoint and treats `HEAD` and `GET` as an identical request.
> Treat HEAD and GET as an identical request

- src/Tus/Client.php
- tests/Tus/ClientTest.php
> Accept all guzzle options in tus client

- src/Tus/Client.php
- src/Tus/Server.php
- tests/Tus/ClientTest.php
- tests/Tus/ServerTest.php
> Add missing headers in client

- src/Tus/AbstractTus.php
- src/Tus/Client.php
- src/Tus/Server.php
- tests/Tus/ServerTest.php
> [Issue fix/#96] Add missing checks in patch request #96

- src/Tus/Client.php
- tests/Tus/ClientTest.php
According to https://tus.io/protocols/resumable-upload.html#upload-metadata the Upload-Metadata header could contain multiple items.
> Set additional metadata in Upload-Metadata header

- src/Response.php
Fixes #165.
Actually, there was no dependency on `iconv` in composer.
> Remove iconv filename fallback. Prefer using Symfony built-in.

- src/Request.php
- tests/RequestTest.php
> Make spaces great again

- src/File.php
- src/Request.php
- src/Tus/Server.php
- tests/FileTest.php
- tests/Tus/ServerTest.php
Fixes #163.
I needed this functionality more or less, so I've given a crack at it. 
Screenshot below is from Symfony dump for file upload completion event, which previously did not contain any user sent metadata.
There are no tests yet added, wanted to have your opinion on this approach first.
> Save user sent metadata

- src/File.php
- src/Tus/Server.php
Currently, TUS PHP does not work with stream wrappers from cloud providers such as [AWS S3](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html).
This pull request makes TUS PHP compatible with stream wrappers and cloud providers storages.
Regarding `DIRECTORY_SEPARATOR`, there is no need to use (for this use case) it since Windows handles the slash for directories very well.
Regarding `APPEND_BINARY`, the cloud provider storages can only open a read or write stream, but not both.
> Add support of the cloud providers storages

- README.md
- composer.json
- docker/base/Dockerfile
- docker/base/configs/php.ini
I have made some improvement on tus-base image to run unit test coverage and allow generate of unit test coverage. This is helpful in cases where we use CI tools for code coverage.
- added xdebug to tus-base image.
- removed open_basedir restriction from *php.ini* which is ok for local development purpose.
- added command `test-coverage` which we can run as `composer test-coverage`
```bash
$ docker exec tus-php-server composer test-coverage
```
> add xdebug to tus-base image

- src/Cache/FileStore.php
- src/Cache/RedisStore.php
- src/Commands/ExpirationCommand.php
- src/Config.php
- src/Config/client.php
- src/Config/server.php
- src/File.php
- src/Middleware/Cors.php
- src/Middleware/Middleware.php
- src/Request.php
- src/Response.php
- src/Tus/AbstractTus.php
- src/Tus/Client.php
- src/Tus/Server.php
The `native_function_invocation` option within PHP CS Fixer was used for this issue.
> PHP CS fixer command executed

- .php_cs
- README.md
- composer.json
- src/Cache/FileStore.php
- src/Cache/RedisStore.php
- src/Config.php
- src/Config/client.php
- src/Config/server.php
- src/File.php
- src/Middleware/Cors.php
- src/Request.php
- src/Response.php
- src/Tus/AbstractTus.php
- src/Tus/Client.php
- src/Tus/Server.php
- tests/FileTest.php
- tests/Fixtures/config.php
- tests/Middleware/MiddlewareTest.php
- tests/RequestTest.php
- tests/Tus/ClientTest.php
- tests/Tus/ServerTest.php
- tests/bootstrap.php
This PR
- Adds PHP-CS-Fixer config `.php_cs` file.
- Reverts a part of #193 and
- Runs cs-fixer with `native_function_invocation` option in [`compiler_optimized` mode](https://github.com/php/php-src/blob/f2db305fa4e9bd7d04d567822687ec714aedcdb5/Zend/zend_compile.c#L3872).
> Add PHP-CS-Fixer config, use native_function_invocation option only for compiler optimized methods

- docker/base/Dockerfile
- docker/base/configs/www.conf
- docker/client/configs/default.conf
- docker/server/configs/default.conf
✅ Update docker compose to use [phpearth docker/php7.4]
**Examples Tested**
✅ Test basic upload
✅ Test partial upload
✅ Test uppy client upload
**Change Log**
✅php-mcrypt has been replaced with php-openssl
- php-openssl which seems to work the same. `php-mcrypt` has been deprecated since  PHP7.2 so had to be replaced with alternative. Please look at this ticket for more insights into it.
**Current Limitation**
❌ php7.4-xdebug Php extension is missing on Alpine Ofice Repository. So, we either have to compile it manually or wait until it's available on Official Repository.
[phpearth docker/php7.4]: https://github.com/phpearth/docker-php/blob/master/docker/7.4-nginx.Dockerfile
> Update docker image to use php7.4 phpearth image

- .travis.yml
[APCu](https://www.php.net/manual/en/book.apcu.php) extension in travis is not enabled after installation in PHP >= 7.3
**Before**
**After**
> ci: Enable APCu extension for PHP >= 7.3

- src/Commands/ExpirationCommand.php
From SF5 [upgrade.md](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md):
`Removed support for returning null from Command::execute(), return 0 instead`
Error with current code:
```
PHP Fatal error:  Uncaught TypeError: Return value of "TusPhp\Commands\ExpirationCommand::execute()" must be of the type int, NULL returned. in /srv/api/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /srv/api/vendor/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /srv/api/vendor/symfony/console/Application.php(265): Symfony\Component\Console\Application->doRunCommand(Object(TusPhp\Commands\ExpirationCommand), …
```
> SF5 commands must return int

- bin/tus
This was causing additional output from commands even when passing the `--quiet` flag. Any output from commands used as a cronjob causes cron to notify the administrator via email.
To test, run `vendor/bin/tus tus:expired -q`. Before, it'd print an empty line. After, there is no output at all. (Alternatively, run `vendor/bin/tus` without any arguments to get the usage message, and notice the difference in newlines above the message.)
> Remove newline in bin/tus causing extra output

- composer.json
See https://github.com/symfony/http-foundation/commit/63f42630839c6e2b097ae4a183ca9d3992ccd80a
> dep: symfony/mime is now explicitly required to guess the mime type

- src/Tus/Client.php
> feat (TUS) 280: pass headers to sub-requests

- src/Response.php
- tests/ResponseTest.php
> Response::create is deprecated since Symfony 5.1

- tests/Tus/ClientTest.php
- tests/Tus/ServerTest.php
This commit fixes Composer autoloader deprecation notices:
Deprecation Notice: Class TusPhp\Test\ServerTest located in
./tests/Tus/ServerTest.php does not comply with psr-4
autoloading standard.
> Fix namespace declaration

- docker/base/Dockerfile
- docker/base/configs/www.conf
- docker/client/configs/default.conf
- docker/server/configs/default.conf
Since [phpearth/docker-php](https://github.com/phpearth/docker-php) is still using `PHP7.4.0-alpha1`, we are reverting back to 7.3 until we find better alternative.
> ci: Downgrade dev php version to 7.3

- src/Tus/Server.php
- tests/Tus/ServerTest.php
> core: Ignore Tus-Resumable header in OPTIONS request

- src/Tus/Client.php
- tests/Tus/ClientTest.php
in case of an 4xx error Guzzle throws a ClientException and the response is inside of that
fixes #323
> handle Guzzle ClientException

- src/Tus/Client.php
- tests/Tus/ClientTest.php
TUS can transfer data already on resource creation (if creation-with-upload﻿ extension is enabled) see https://tus.io/protocols/resumable-upload.html#creation-with-upload﻿
the new function allows us to use that extension in the client
> Add function to upload data on resource creation

- .travis.yml
Some constants are only available in certain modes in Xdebug 3. This is fixed in the latest Xdebug release but not yet available in the version used by Travis. Also, it won't hurt to run xdebug in coverage mode.
See: https://github.com/xdebug/xdebug/pull/699
> chore: Run phpunit with XDEBUG_MODE=coverage

- src/Request.php
- tests/RequestTest.php
This PR make some changes on metadata extraction to align with the protocol.
- The value MAY be empty. In these cases, the space, which would normally separate the key and the value, MAY be left out.
- Even though the protocol doesn't say anything about empty space after comma and key, the official implementation seems to trim extra spaces.
Ref: https://tus.io/protocols/resumable-upload.html#upload-metadata
Fixes #378
> fix: Align metadata extraction with protocol

- src/Request.php
Fixes:
```
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
```
> fix: do not pass null to strpos

- src/Cache/RedisStore.php
Fixes:
```
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated
```
> fix: do not pass null to json_decode()

- src/Tus/Server.php
- tests/Tus/ServerTest.php
> fix: Return 410 if cache is expired for inflight requests

- src/Cache/FileStore.php
- src/File.php
On Windows write data that FileStore.php is programmed cause 
`Write of xx bytes failed with errno=13 Permission denied`
This is because the program call file_put_contents and filesize (that always return 0) methods on a locked file
From 14 PHPUnit test on Windows errors, on my implementation now have only 3 (that is non-related), this don't add any errors, only fix some existent errors
> fix: Lock file on windows

- .github/workflows/ci.yml
- README.md
- composer.json
PHP `7.*` and `8.0` has already reached EOL, we won't support them from the next release.
https://www.php.net/supported-versions.php
> Drop support for PHP 7.*
