ankitpokhrel/tus-php

README.md, src/File.php, src/Tus/Client.php, src/Tus/Server.php, tests/FileTest.php, tests/Tus/ClientTest.php, tests/Tus/ServerTest.php
https://tus.io/protocols/resumable-upload.html#checksum
=> Add support for tus checksum extension

README.md, bin/console, composer.json, composer.lock, phpunit.xml, src/Cache/AbstractCache.php, src/Cache/Cacheable.php, src/Cache/FileStore.php, src/Cache/RedisStore.php, src/Commands/ExpirationCommand.php, src/Tus/AbstractTus.php, src/Tus/Server.php, tests/Cache/FileStoreTest.php, tests/Cache/RedisStoreTest.php, tests/Tus/ServerTest.php
https://tus.io/protocols/resumable-upload.html#expiration
**Todo**
=> Add support for tus expiration extension

.dockerignore, README.md, k8s/cron.yml, src/Tus/Server.php, tests/Tus/ServerTest.php
=> Add k8s job to run tus expiration command

composer.json
=> Remove at dev tag as min stability is dev

composer.json
=> Use stable version for symfony/console

README.md, bin/tus, composer.json, k8s/cron.yml
=> Make bin/console command available as composer binary

README.md, example/partial.php, src/Cache/AbstractCache.php, src/Cache/Cacheable.php, src/Cache/FileStore.php, src/Cache/RedisStore.php, src/File.php, src/Request.php, src/Tus/AbstractTus.php, src/Tus/Client.php, src/Tus/Server.php, tests/Cache/FileStoreTest.php, tests/Cache/RedisStoreTest.php, tests/FileTest.php, tests/Fixtures/FileFixture.php, tests/RequestTest.php, tests/Tus/ClientTest.php, tests/Tus/ServerTest.php
https://tus.io/protocols/resumable-upload.html#concatenation
**Todo**
=> Add support for tus concatenation extension

src/Cache/FileStore.php, tests/Cache/FileStoreTest.php
=> Make Filestore cache path configurable via constructor

src/Response.php, src/Tus/Server.php, tests/ResponseTest.php, tests/Tus/ServerTest.php
=> Add missing CORS headers in all response

.gitignore, README.md, composer.json, composer.lock, src/Cache/AbstractCache.php, src/Cache/FileStore.php, src/Cache/RedisStore.php, src/Tus/AbstractTus.php, src/Tus/Client.php, src/Tus/Server.php, tests/Tus/AbstractTusTest.php, tests/Tus/ClientTest.php, tests/Tus/ServerTest.php
=> Compatibility with uppy

README.md, src/Middleware/Cors.php, src/Middleware/GlobalHeaders.php, src/Middleware/Middleware.php, src/Middleware/MiddlewareInterface.php, src/Middleware/TusMiddleware.php, src/Response.php, src/Tus/Server.php, tests/Fixtures/TestMiddleware.php, tests/Middleware/CorsTest.php, tests/Middleware/GlobalHeadersTest.php, tests/Middleware/MiddlewareTest.php, tests/ResponseTest.php, tests/Tus/ServerTest.php
=> Add basic middleware support

README.md, example/basic/upload.php, example/basic/verify.php, example/partial/partial.php, src/Tus/Client.php, tests/Tus/ClientTest.php
=> Remove cache dependency from Client

README.md, composer.json, src/Config.php, src/Config/client.php, src/Config/server.php, src/Tus/AbstractTus.php, src/Tus/Client.php, tests/Tus/ClientTest.php, tests/Tus/ServerTest.php
=> Fix creation extension implementation

composer.json, src/Cache/FileStore.php, src/Tus/Server.php, tests/Cache/FileStoreTest.php
=> Add shared locks to FileStore

src/Tus/Client.php, tests/Tus/ClientTest.php
=> Verify expiry date-time during upload

src/Tus/Server.php, tests/Tus/ServerTest.php
Issue #120.
UploadMerged and UploadCreated events were missing either one or both of key and checksum.
=>  #120 - Added key and checksum to some events

.gitattributes
=> Remove /bin/tus from export ignore

src/Middleware/GlobalHeaders.php, tests/Middleware/GlobalHeadersTest.php
Fixes https://github.com/ankitpokhrel/tus-php/issues/134
=> Fix Tus-Resumable header missing from OPTIONS response

README.md, src/Config/client.php, src/Config/server.php
=> Fix redis env check

composer.json
=> Fix event-dispatcher version

.github/ISSUE_TEMPLATE/bug_report.md, src/Request.php, tests/RequestTest.php
=> Validate file name passed in upload metadata

src/Tus/Client.php
This bug was introduced by #152
=> Fix partial upload

tests/FileTest.php, tests/RequestTest.php, tests/Tus/ClientTest.php
=> Make test coverage 100%

src/Tus/Client.php
Fixes https://github.com/ankitpokhrel/tus-php/issues/140
=> Replaced uniqid with Ramsey\Uuid\Uuid +uuid4()

example/uppy/index.html
Fixes https://github.com/ankitpokhrel/tus-php/issues/187
=> Fixed download link in uppy example

src/Tus/Server.php
=> Dispatching event with response headers set

.github/workflows/ci.yml, composer.json
Updating cs fixer lint command.
=> Updating cs fixer lint command

README.md
=> Upload key is mandatory.

.github/workflows/ci.yml
Shamelessly inspired/copied from https://github.com/sebastianbergmann/phpunit/blob/master/.github/workflows/ci.yml
=> Build CI on all push and improve git actions

composer.json
See: 
- https://github.com/advisories/GHSA-x92h-wmg2-6hp7
- https://github.com/advisories/GHSA-xhh6-956q-4q69
=> Upgrade symfony packages

docker/base/Dockerfile, docker/base/configs/php.ini
This PR updates dev docker setup to:
- add APCu extension
- remove soap extension
=> dev: Install APCu extension

src/Tus/AbstractTus.php
=> Allow to inject dispatcher

composer.json
https://github.com/advisories/GHSA-mcx4-f5f5-4859
=> dep: Bump symfony/http-foundation

.travis.yml
This pull request fixes an error that would occur when running the test suite on Travis CI.
I've removed the line that installs the `apcu` in the `travis.yml` file, Travis' config file.
This PR addresses #300.
=> Fix Travis CI build issue

.travis.yml
This PR fixes the issue with #301 
Fixes #300
=> ci: Add apcu in travis

Makefile, README.md, bin/lint.sh, composer.json
Broken by: https://github.com/ankitpokhrel/tus-php/pull/307/commits/b2f3b3c2385f07aa3febcd91a0740921232d898a
=> dev: Fix linter

.github/workflows/ci.yml, composer.json
continuation of #307 
v2.18 supports PHP v8
=> Update PHP CS Fixer to v2.18

composer.json, src/Tus/Client.php, tests/Tus/ClientTest.php
This PR updates dev dependencies to fix broken tests because of deprecated methods.
=> dep: Update dev dependencies

src/Cache/FileStore.php, tests/Cache/FileStoreTest.php
This fixes `410 Gone` error due to data race on file cache.
=> fix: Data race in file cache

composer.json
resolves https://github.com/ankitpokhrel/tus-php/issues/373
Not sure if more needs to be done.
=> chore: allow symfony 6

src/Config.php, src/Config/client.php, src/Config/server.php, tests/ConfigTest.php, tests/Fixtures/config.php
=> feat: Make file cache path configurable

.github/workflows/ci.yml, README.md
See https://github.com/badges/shields/issues/8671
=> ci: Fix push branch and badge URL
